mappings:
  OGDeterminers: TractorCow\OpenGraph\Constants\OGDeterminers
  OGGenders: TractorCow\OpenGraph\Constants\OGGenders
  OGTypes: TractorCow\OpenGraph\Constants\OGTypes
  OpenGraphObjectExtension: TractorCow\OpenGraph\Extensions\OpenGraphObjectExtension
  OpenGraphSiteConfigExtension: TractorCow\OpenGraph\Extensions\OpenGraphSiteConfigExtension
  IOGApplication: TractorCow\OpenGraph\Interfaces\IOGApplication
  IOpenGraphObjectBuilder: TractorCow\OpenGraph\Interfaces\IOpenGraphObjectBuilder
  IOGObject: TractorCow\OpenGraph\Interfaces\ObjectTypes\IOGObject
  IOGObjectExplicit: TractorCow\OpenGraph\Interfaces\ObjectTypes\IOGObjectExplicit
  IOGObjectRequired: TractorCow\OpenGraph\Interfaces\ObjectTypes\IOGObjectRequired
  IOGMusic: TractorCow\OpenGraph\Interfaces\Music\IOGMusic
  IOGMusicSongList: TractorCow\OpenGraph\Interfaces\Music\IOGMusicSongList
  IOGMusicAlbum: TractorCow\OpenGraph\Interfaces\Music\IOGMusicAlbum
  IOGMusicPlaylist: TractorCow\OpenGraph\Interfaces\Music\IOGMusicPlaylist
  IOGMusicRadioStation: TractorCow\OpenGraph\Interfaces\Music\IOGMusicRadioStation
  IOGMusicSong: TractorCow\OpenGraph\Interfaces\Music\IOGMusicSong
  IOGSongAlbum: TractorCow\OpenGraph\Interfaces\Music\Relations\IOGSongAlbum
  IOGAuthoredTagged: TractorCow\OpenGraph\Interfaces\Other\IOGAuthoredTagged
  IOGTagged: TractorCow\OpenGraph\Interfaces\Other\IOGTagged
  IOGArticle: TractorCow\OpenGraph\Interfaces\Other\IOGArticle
  IOGBook: TractorCow\OpenGraph\Interfaces\Other\IOGBook
  IOGProfile: TractorCow\OpenGraph\Interfaces\Other\IOGProfile
  IOGWebsite: TractorCow\OpenGraph\Interfaces\Other\IOGWebsite
  IMediaFile: TractorCow\OpenGraph\Interfaces\Other\Relations\IMediaFile
  IOGVideo: TractorCow\OpenGraph\Interfaces\Video\IOGVideo
  IOGVideoEpisode: TractorCow\OpenGraph\Interfaces\Video\IOGVideoEpisode
  IOGVideoMovie: TractorCow\OpenGraph\Interfaces\Video\IOGVideoMovie
  IOGVideoOther: TractorCow\OpenGraph\Interfaces\Video\IOGVideoOther
  IOGVideoTVShow: TractorCow\OpenGraph\Interfaces\Video\IOGVideoTVShow
  IOGVideoActor: TractorCow\OpenGraph\Interfaces\Video\Relations\IOGVideoActor
  OGMusic: TractorCow\OpenGraph\ObjectBuilders\Music\AbstractOGMusic
  OGMusicAlbum: TractorCow\OpenGraph\ObjectBuilders\Music\OGMusicAlbum
  OGMusicPlaylist: TractorCow\OpenGraph\ObjectBuilders\Music\OGMusicPlaylist
  OGMusicRadioStation: TractorCow\OpenGraph\ObjectBuilders\Music\OGMusicRadioStation
  OGMusicSong: TractorCow\OpenGraph\ObjectBuilders\Music\OGMusicSong
  OpenGraphBuilder: TractorCow\OpenGraph\ObjectBuilders\OpenGraphBuilder
  OGArticle: TractorCow\OpenGraph\ObjectBuilders\Other\OGArticle
  OGBook: TractorCow\OpenGraph\ObjectBuilders\Other\OGBook
  OGProfile: TractorCow\OpenGraph\ObjectBuilders\Other\OGProfile
  OGWebsite: TractorCow\OpenGraph\ObjectBuilders\Other\OGWebsite
  OGVideo: TractorCow\OpenGraph\ObjectBuilders\Video\AbstractOGVideo
  OGVideoEpisode: TractorCow\OpenGraph\ObjectBuilders\Video\OGVideoEpisode
  OGVideoMovie: TractorCow\OpenGraph\ObjectBuilders\Video\OGVideoMovie
  OGVideoOther: TractorCow\OpenGraph\ObjectBuilders\Video\OGVideoOther
  OGVideoTVShow: TractorCow\OpenGraph\ObjectBuilders\Video\OGVideoTVShow
  OpenGraph: TractorCow\OpenGraph\OpenGraph
